meta_product_name: "W3C Web Sustainibility Guidelines"
meta_title: "Web Sustainibility Guidelines – explore and learn for more sustainable web"
meta_description: "Explore W3C's web sustainability guidelines with ease at WebSustainabilityGuidelines.com. Our user-friendly platform simplifies your journey through these essential guidelines, helping you identify and focus on the right improvements for your specific web project. Start enhancing your site's sustainability today."
meta_image: "cover.png"
# should exist in `app/assets/images/`
